
<?php

//ATRIBUINDO VALOR AS VARIÁVEIS E ARRAY/LISTA//


/*$VAR = "Olá mundo 1 !";
echo $VAR;
echo "<br>";
$VAR2 = "Olá mundo! 2 ";
echo $VAR2;
echo "<br>";
$varnumber = 5;
echo $varnumber;
$vararray = ["ola gatinhas", "gatinhos", "não binaries"];
echo $vararray;
var_dump($vararray);
echo $vararray[1];
echo count ($vararray);*/
//$array = explode(" ", $VAR);//
//var_dump($array);//
//EXPLODE SEPARA/QUEBRA A VARIÁVEL, EM UM ARRAY, OU SEJA//
//CADA PALAVRA VAI VIRAR UM ITEM/POSIÇÃO DO ARRAY//
/*$varimplode = implode ("*", $array);
echo "<br>";
var_dump($varimplode);*/




//CONDIÇÕES IF ELSEIF ELSE//

/*$boolean = true;

if ($boolean == true){
    echo "é verdade";
}
elseif($boolean == false){
    echo "é mentira";
   
}else {
echo "não é verdade nem mentira";

}*/



//LAÇO DE REPETIÇÃO FOR, WHILE, DO WHILE, FOREACH.//

 /*for ($i = 0; $i < 5; $i++) {
    echo $i + 1;
}*/

echo "<br>";
 
/*$w = 0;
 while($w <= 5) {
    echo $w;
    $w++;
 }
 
 echo "<br>";
 
 $dw = 0; 
 do {
    echo $dw;
    $dw++;
 } while ($dw <= 5);
 echo "<br>";

 $array = [0, 1, 2, 3, 4, 5];
 foreach ($array as $number){
    echo $number;
 }*/


 // FUNÇÕES//

 /*function funcaofor(){
    echo "Função for!";
    for ($i = 0; $i < 5; $i++) {
        echo $i;
 }
 echo "<br>";
}
funcaofor()

function printar() {
    $var = 1;
    echo $var;
    echo "<br>";
}
  
for ($i = 0; $i <=7; $i++) {
    printar();
}*/


?>

















