<?php
// AULA 1 echo "PÁGINA PRINCIPAL";//

/*$array = ["Olá", 21, false];
var_dump($array);*/
//para concatenar//
/*$string1 = "Olá";
$string2 = "Mundo";
$string3 = $string1 . $string2;
echo $string3;*/


/*function funcao($var){
   
    echo $var;
}

$var2 = "Teste2";
funcao($var2);*/



/*function media($prova1, $prova2){
    $media = ($prova1 + $prova2) / 2;
    return $media;
}


$nota1 = 10;
$nota2 = 2;
$notafinal;
$notafinal = media($nota1, $nota2);
echo $notafinal;*/

//$get = $_GET["get"];
//echo $get;


$number = $_GET["number"];
var_dump($number);
echo "<br>";
$number = (INT) $number;
var_dump($number);
echo "<br>";
echo $number;







?>

















